name: Ardu.Common - CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    outputs:
      nbgv: ${{ steps.nbgv.outputs.SemVer2 }}
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: NBGitVersioning
      id: nbgv
      uses: dotnet/nbgv@master
      with:
        setAllVars: true
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack DotNet
      run: dotnet pack --no-restore --configuration ${{ inputs.configuration }} ${{ inputs.solutionFile }}
      working-directory: ${{ inputs.srcFolder }}
    # - name: Create NuGet Artifacts
    #   if: inputs.createArtifacts == true
    #   uses: actions/upload-artifact@master
    #   with:
    #     name: nuget
    #     path: '**/*.nupkg'